-- Tabla currículo simplificada: solo curso, asignatura, tema
-- Ejecutar en: Supabase Dashboard → SQL Editor
-- REEMPLAZA la tabla anterior (estructura compleja) por esta más simple

DROP TABLE IF EXISTS public.curriculo_temas CASCADE;

CREATE TABLE public.curriculo_temas (
  id         SERIAL PRIMARY KEY,
  curso      TEXT NOT NULL,
  asignatura TEXT NOT NULL,
  tema       TEXT NOT NULL
);

ALTER TABLE public.curriculo_temas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "curriculo_read_all"
  ON public.curriculo_temas FOR SELECT
  USING (TRUE);

CREATE POLICY "curriculo_admin_all"
  ON public.curriculo_temas FOR ALL
  USING (is_admin());

CREATE INDEX curriculo_temas_curso_asig_idx
  ON public.curriculo_temas (curso, asignatura);

-- ============================================================
-- DATOS: ESO
-- ============================================================

-- 1º ESO
INSERT INTO public.curriculo_temas (curso, asignatura, tema) VALUES
('1º ESO','Matemáticas','Números naturales, enteros y fracciones'),
('1º ESO','Matemáticas','Divisibilidad'),
('1º ESO','Matemáticas','Potencias y raíces'),
('1º ESO','Matemáticas','Proporcionalidad y porcentajes'),
('1º ESO','Matemáticas','Iniciación al álgebra: expresiones y ecuaciones sencillas'),
('1º ESO','Matemáticas','Figuras planas: perímetros y áreas'),
('1º ESO','Matemáticas','Sistema de coordenadas'),
('1º ESO','Matemáticas','Tablas y gráficos estadísticos'),
('1º ESO','Matemáticas','Azar y probabilidad'),
('1º ESO','Matemáticas','Gestión emocional y trabajo en equipo'),
('1º ESO','Lengua Castellana y Literatura','Realidad plurilingüe de España'),
('1º ESO','Lengua Castellana y Literatura','Comunicación oral: escuchar y hablar'),
('1º ESO','Lengua Castellana y Literatura','Comprensión lectora y producción escrita'),
('1º ESO','Lengua Castellana y Literatura','El texto narrativo y descriptivo'),
('1º ESO','Lengua Castellana y Literatura','Géneros literarios'),
('1º ESO','Lengua Castellana y Literatura','Lectura de obras literarias'),
('1º ESO','Lengua Castellana y Literatura','Gramática: categorías y oración simple'),
('1º ESO','Lengua Castellana y Literatura','Léxico y ortografía'),
('1º ESO','Valenciano','Diversitat lingüística i comunicació oral'),
('1º ESO','Valenciano','Comprensió lectora i producció escrita'),
('1º ESO','Valenciano','El text narratiu i descriptiu'),
('1º ESO','Valenciano','Gèneres literaris'),
('1º ESO','Valenciano','Lectura d''obres en valencià'),
('1º ESO','Valenciano','Gramàtica: categories i oració simple'),
('1º ESO','Valenciano','Lèxic i ortografia valenciana'),
('1º ESO','Inglés','Comprensión oral y escrita'),
('1º ESO','Inglés','Producción e interacción oral y escrita'),
('1º ESO','Inglés','Funciones comunicativas cotidianas'),
('1º ESO','Inglés','Gramática y léxico de nivel'),
('1º ESO','Inglés','Estrategias de mediación y comprensión'),
('1º ESO','Inglés','Aspectos culturales y plurilingüismo'),
('1º ESO','Biología y Geología','Método científico y trabajo de laboratorio'),
('1º ESO','Biología y Geología','La Tierra en el universo y el Sistema Solar'),
('1º ESO','Biología y Geología','La geosfera: minerales y rocas'),
('1º ESO','Biología y Geología','La atmósfera'),
('1º ESO','Biología y Geología','La hidrosfera'),
('1º ESO','Biología y Geología','La célula'),
('1º ESO','Biología y Geología','Clasificación de los seres vivos: los cinco reinos'),
('1º ESO','Biología y Geología','Invertebrados y vertebrados'),
('1º ESO','Biología y Geología','Las plantas'),
('1º ESO','Biología y Geología','Ecosistemas'),
('1º ESO','Geografía e Historia','El planeta Tierra: relieve, clima y paisajes'),
('1º ESO','Geografía e Historia','Medio físico de Europa y España'),
('1º ESO','Geografía e Historia','La Prehistoria'),
('1º ESO','Geografía e Historia','Las primeras civilizaciones: Mesopotamia y Egipto'),
('1º ESO','Geografía e Historia','Grecia'),
('1º ESO','Geografía e Historia','Roma'),
('1º ESO','Francés','Iniciación a la comprensión y producción'),
('1º ESO','Francés','Funciones comunicativas básicas'),
('1º ESO','Francés','Léxico elemental'),
('1º ESO','Francés','Cultura francófona');

-- 2º ESO
INSERT INTO public.curriculo_temas (curso, asignatura, tema) VALUES
('2º ESO','Matemáticas','Números enteros, fracciones y decimales'),
('2º ESO','Matemáticas','Proporcionalidad'),
('2º ESO','Matemáticas','Potencias y raíces cuadradas'),
('2º ESO','Matemáticas','Álgebra: ecuaciones de primer grado'),
('2º ESO','Matemáticas','Teorema de Pitágoras'),
('2º ESO','Matemáticas','Figuras y cuerpos geométricos: áreas y volúmenes'),
('2º ESO','Matemáticas','Funciones y gráficas: iniciación'),
('2º ESO','Matemáticas','Estadística y probabilidad'),
('2º ESO','Lengua Castellana y Literatura','Comunicación oral y escrita'),
('2º ESO','Lengua Castellana y Literatura','Tipologías textuales'),
('2º ESO','Lengua Castellana y Literatura','El texto instructivo y expositivo'),
('2º ESO','Lengua Castellana y Literatura','Géneros literarios: narrativa, lírica, teatro'),
('2º ESO','Lengua Castellana y Literatura','Gramática: sintaxis de la oración simple'),
('2º ESO','Lengua Castellana y Literatura','Léxico y ortografía'),
('2º ESO','Valenciano','Comunicació oral i escrita'),
('2º ESO','Valenciano','Tipologies textuals'),
('2º ESO','Valenciano','El text instructiu i expositiu'),
('2º ESO','Valenciano','Gèneres literaris: narrativa, lírica, teatre'),
('2º ESO','Valenciano','Gramàtica: sintaxi de l''oració simple'),
('2º ESO','Valenciano','Lèxic i ortografia valenciana'),
('2º ESO','Inglés','Comprensión y producción oral y escrita'),
('2º ESO','Inglés','Funciones comunicativas de nivel intermedio'),
('2º ESO','Inglés','Gramática y léxico de nivel'),
('2º ESO','Inglés','Estrategias de mediación'),
('2º ESO','Inglés','Aspectos culturales'),
('2º ESO','Física y Química','Método científico, magnitudes y Sistema Internacional'),
('2º ESO','Física y Química','Propiedades de la materia y estados de agregación'),
('2º ESO','Física y Química','Modelo cinético-molecular'),
('2º ESO','Física y Química','Sustancias puras y mezclas: separación'),
('2º ESO','Física y Química','La energía y sus formas'),
('2º ESO','Física y Química','El cambio físico y químico: introducción a la reacción química'),
('2º ESO','Geografía e Historia','La Europa feudal'),
('2º ESO','Geografía e Historia','El islam y Al-Ándalus'),
('2º ESO','Geografía e Historia','Los reinos cristianos peninsulares'),
('2º ESO','Geografía e Historia','La ciudad medieval'),
('2º ESO','Geografía e Historia','El Renacimiento y el Humanismo'),
('2º ESO','Geografía e Historia','La Edad Moderna: siglos XV-XVIII'),
('2º ESO','Geografía e Historia','Los descubrimientos geográficos');

-- 3º ESO
INSERT INTO public.curriculo_temas (curso, asignatura, tema) VALUES
('3º ESO','Matemáticas','Números racionales y reales'),
('3º ESO','Matemáticas','Potencias y notación científica'),
('3º ESO','Matemáticas','Polinomios y ecuaciones/sistemas'),
('3º ESO','Matemáticas','Sucesiones'),
('3º ESO','Matemáticas','Geometría: semejanza y cuerpos geométricos'),
('3º ESO','Matemáticas','Funciones lineales y cuadráticas'),
('3º ESO','Matemáticas','Estadística y probabilidad'),
('3º ESO','Lengua Castellana y Literatura','Variedades del español y lenguas de España'),
('3º ESO','Lengua Castellana y Literatura','Comunicación oral formal'),
('3º ESO','Lengua Castellana y Literatura','Texto expositivo-argumentativo'),
('3º ESO','Lengua Castellana y Literatura','Literatura medieval y de los Siglos de Oro'),
('3º ESO','Lengua Castellana y Literatura','Sintaxis de la oración'),
('3º ESO','Lengua Castellana y Literatura','Léxico y ortografía'),
('3º ESO','Valenciano','Varietats del valencià i sociolingüística'),
('3º ESO','Valenciano','Comunicació oral formal'),
('3º ESO','Valenciano','Text expositiu-argumentatiu'),
('3º ESO','Valenciano','Literatura medieval i dels Segles d''Or en valencià'),
('3º ESO','Valenciano','Sintaxi de l''oració'),
('3º ESO','Valenciano','Lèxic i ortografia valenciana'),
('3º ESO','Inglés','Comprensión y producción oral y escrita (B1)'),
('3º ESO','Inglés','Funciones comunicativas de nivel intermedio'),
('3º ESO','Inglés','Gramática y léxico de nivel B1'),
('3º ESO','Inglés','Estrategias de mediación'),
('3º ESO','Inglés','Aspectos socioculturales'),
('3º ESO','Biología y Geología','La célula y los tejidos'),
('3º ESO','Biología y Geología','La salud y la enfermedad'),
('3º ESO','Biología y Geología','Nutrición: aparatos digestivo, respiratorio, circulatorio y excretor'),
('3º ESO','Biología y Geología','Relación: sistema nervioso, endocrino y órganos de los sentidos'),
('3º ESO','Biología y Geología','Reproducción humana'),
('3º ESO','Biología y Geología','Geología externa e interna: relieve y su modelado'),
('3º ESO','Física y Química','Método científico'),
('3º ESO','Física y Química','Estructura atómica, isótopos y modelos atómicos'),
('3º ESO','Física y Química','El Sistema Periódico'),
('3º ESO','Física y Química','Uniones entre átomos'),
('3º ESO','Física y Química','Formulación y nomenclatura de compuestos binarios (IUPAC)'),
('3º ESO','Física y Química','La reacción química y cálculos estequiométricos'),
('3º ESO','Física y Química','Ley de conservación de la masa'),
('3º ESO','Física y Química','Química, sociedad y medio ambiente'),
('3º ESO','Geografía e Historia','Población y movimientos migratorios'),
('3º ESO','Geografía e Historia','El espacio urbano y rural'),
('3º ESO','Geografía e Historia','Los sectores económicos'),
('3º ESO','Geografía e Historia','Globalización y organización política'),
('3º ESO','Geografía e Historia','España y la Comunitat Valenciana'),
('3º ESO','Geografía e Historia','Los ODS y el desarrollo sostenible');

-- 4º ESO
INSERT INTO public.curriculo_temas (curso, asignatura, tema) VALUES
('4º ESO','Matemáticas A','Números reales y porcentajes'),
('4º ESO','Matemáticas A','Matemática financiera básica'),
('4º ESO','Matemáticas A','Álgebra aplicada'),
('4º ESO','Matemáticas A','Funciones y gráficas'),
('4º ESO','Matemáticas A','Estadística y probabilidad aplicadas'),
('4º ESO','Matemáticas B','Números reales y radicales'),
('4º ESO','Matemáticas B','Polinomios y fracciones algebraicas'),
('4º ESO','Matemáticas B','Ecuaciones, inecuaciones y sistemas'),
('4º ESO','Matemáticas B','Trigonometría'),
('4º ESO','Matemáticas B','Geometría analítica'),
('4º ESO','Matemáticas B','Funciones: polinómicas, exponenciales, logarítmicas'),
('4º ESO','Matemáticas B','Estadística y probabilidad'),
('4º ESO','Lengua Castellana y Literatura','Comunicación y tipologías textuales avanzadas'),
('4º ESO','Lengua Castellana y Literatura','Literatura del siglo XVIII y XIX: Romanticismo y Realismo'),
('4º ESO','Lengua Castellana y Literatura','Literatura del siglo XX: Generación del 98, del 27 y contemporánea'),
('4º ESO','Lengua Castellana y Literatura','Sintaxis de la oración compuesta'),
('4º ESO','Lengua Castellana y Literatura','Léxico y ortografía'),
('4º ESO','Valenciano','Comunicació i tipologies textuals avançades'),
('4º ESO','Valenciano','Literatura valenciana contemporànea'),
('4º ESO','Valenciano','Sintaxi avançada'),
('4º ESO','Valenciano','Lèxic i ortografia valenciana'),
('4º ESO','Inglés','Comprensión y producción oral y escrita (B2 inicial)'),
('4º ESO','Inglés','Funciones comunicativas avanzadas'),
('4º ESO','Inglés','Gramática y léxico de nivel'),
('4º ESO','Inglés','Estrategias de mediación'),
('4º ESO','Inglés','Aspectos socioculturales'),
('4º ESO','Geografía e Historia','El siglo XVIII y las revoluciones liberales'),
('4º ESO','Geografía e Historia','La Revolución Industrial'),
('4º ESO','Geografía e Historia','Imperialismo y Primera Guerra Mundial'),
('4º ESO','Geografía e Historia','Periodo de entreguerras y Segunda Guerra Mundial'),
('4º ESO','Geografía e Historia','Guerra Fría y descolonización'),
('4º ESO','Geografía e Historia','España contemporánea: siglos XIX-XX'),
('4º ESO','Geografía e Historia','El mundo actual y la globalización'),
('4º ESO','Biología y Geología','La evolución y la genética'),
('4º ESO','Biología y Geología','Genética molecular y herencia'),
('4º ESO','Biología y Geología','Origen y evolución de los seres vivos'),
('4º ESO','Biología y Geología','Ecología y medio ambiente'),
('4º ESO','Biología y Geología','La dinámica de la Tierra: tectónica de placas'),
('4º ESO','Biología y Geología','Historia de la Tierra'),
('4º ESO','Física y Química','Cinemática y dinámica: movimiento y fuerzas'),
('4º ESO','Física y Química','Energía y trabajo'),
('4º ESO','Física y Química','Estructura atómica y enlace'),
('4º ESO','Física y Química','Reacciones químicas'),
('4º ESO','Física y Química','Química del carbono: introducción'),
('4º ESO','Economía y Emprendimiento','La actividad económica y el emprendimiento'),
('4º ESO','Economía y Emprendimiento','Mercados: oferta y demanda'),
('4º ESO','Economía y Emprendimiento','Economía personal y financiera'),
('4º ESO','Economía y Emprendimiento','El proyecto emprendedor'),
('4º ESO','Latín','El latín y las lenguas romances'),
('4º ESO','Latín','Sistema de la lengua latina: morfología y sintaxis básica'),
('4º ESO','Latín','Textos latinos y traducción'),
('4º ESO','Latín','Léxico y etimología latina'),
('4º ESO','Latín','Civilización romana'),
('4º ESO','Filosofía','El saber filosófico'),
('4º ESO','Filosofía','El ser humano'),
('4º ESO','Filosofía','Conocimiento y verdad'),
('4º ESO','Filosofía','Ética y filosofía moral'),
('4º ESO','Filosofía','Filosofía política'),
('4º ESO','Filosofía','Estética: introducción');

-- ============================================================
-- DATOS: 1º BACHILLERATO
-- ============================================================

INSERT INTO public.curriculo_temas (curso, asignatura, tema) VALUES
-- Lengua (I)
('1º Bachillerato','Lengua Castellana y Literatura','Comunicación y tipologías textuales'),
('1º Bachillerato','Lengua Castellana y Literatura','Variedades del español'),
('1º Bachillerato','Lengua Castellana y Literatura','Literatura de la Edad Media al siglo XIX'),
('1º Bachillerato','Lengua Castellana y Literatura','Sintaxis avanzada'),
('1º Bachillerato','Lengua Castellana y Literatura','Norma y uso del español'),
-- Valenciano (I y II comparten temas de bloque)
('1º Bachillerato','Valenciano','Comunicació i textos acadèmics'),
('1º Bachillerato','Valenciano','Sociolingüística del valencià'),
('1º Bachillerato','Valenciano','Literatura valenciana clàssica i contemporànea'),
('1º Bachillerato','Valenciano','Comentari de text'),
-- Inglés I
('1º Bachillerato','Inglés','Comprensión y producción de textos complejos'),
('1º Bachillerato','Inglés','Mediación lingüística e intercultural'),
('1º Bachillerato','Inglés','Gramática y léxico B1-B2'),
('1º Bachillerato','Inglés','Aspectos socioculturales'),
-- Filosofía (obligatoria 1º Bach)
('1º Bachillerato','Filosofía','Qué es la filosofía'),
('1º Bachillerato','Filosofía','Lógica y argumentación'),
('1º Bachillerato','Filosofía','Teoría del conocimiento'),
('1º Bachillerato','Filosofía','Metafísica'),
('1º Bachillerato','Filosofía','Antropología filosófica'),
('1º Bachillerato','Filosofía','Ética'),
('1º Bachillerato','Filosofía','Filosofía política'),
('1º Bachillerato','Filosofía','Estética'),
-- Matemáticas I (Ciencias)
('1º Bachillerato','Matemáticas','Números reales, complejos y logaritmos'),
('1º Bachillerato','Matemáticas','Álgebra y ecuaciones'),
('1º Bachillerato','Matemáticas','Trigonometría'),
('1º Bachillerato','Matemáticas','Geometría analítica plana'),
('1º Bachillerato','Matemáticas','Funciones, límites y derivadas: introducción'),
('1º Bachillerato','Matemáticas','Estadística bidimensional y probabilidad'),
-- Matemáticas Aplicadas I (HH.CC.SS.)
('1º Bachillerato','Matemáticas Aplicadas','Números reales y matemática financiera'),
('1º Bachillerato','Matemáticas Aplicadas','Álgebra: matrices, sistemas y programación lineal'),
('1º Bachillerato','Matemáticas Aplicadas','Funciones, límites y derivadas'),
('1º Bachillerato','Matemáticas Aplicadas','Estadística descriptiva'),
('1º Bachillerato','Matemáticas Aplicadas','Probabilidad'),
-- Historia del Mundo Contemporáneo (HH.CC.SS.)
('1º Bachillerato','Historia del Mundo Contemporáneo','Crisis del Antiguo Régimen y revoluciones liberales'),
('1º Bachillerato','Historia del Mundo Contemporáneo','Revolución Industrial'),
('1º Bachillerato','Historia del Mundo Contemporáneo','Imperialismo'),
('1º Bachillerato','Historia del Mundo Contemporáneo','Las guerras mundiales y el periodo de entreguerras'),
('1º Bachillerato','Historia del Mundo Contemporáneo','Guerra Fría'),
('1º Bachillerato','Historia del Mundo Contemporáneo','Descolonización'),
('1º Bachillerato','Historia del Mundo Contemporáneo','El mundo actual y la globalización'),
-- Economía (HH.CC.SS.)
('1º Bachillerato','Economía','Escasez y costes de oportunidad'),
('1º Bachillerato','Economía','Sistemas económicos'),
('1º Bachillerato','Economía','Oferta, demanda y mercados'),
('1º Bachillerato','Economía','PIB y renta nacional'),
('1º Bachillerato','Economía','Inflación y desempleo'),
('1º Bachillerato','Economía','Política fiscal y monetaria'),
('1º Bachillerato','Economía','Comercio internacional y globalización'),
('1º Bachillerato','Economía','Economía española y valenciana'),
-- Literatura Universal
('1º Bachillerato','Literatura Universal','Literatura del yo y poesía lírica'),
('1º Bachillerato','Literatura Universal','El teatro y sus géneros'),
('1º Bachillerato','Literatura Universal','Lo real y lo fantástico en la narrativa'),
('1º Bachillerato','Literatura Universal','Itinerarios temáticos intertextuales'),
('1º Bachillerato','Literatura Universal','Relaciones literatura-otras artes'),
('1º Bachillerato','Literatura Universal','Creación literaria propia'),
-- Latín I
('1º Bachillerato','Latín','Fonética, morfología nominal y verbal'),
('1º Bachillerato','Latín','Sintaxis de casos y oraciones'),
('1º Bachillerato','Latín','Traducción de textos graduados'),
('1º Bachillerato','Latín','Étimos y latinismos'),
('1º Bachillerato','Latín','Literatura latina'),
('1º Bachillerato','Latín','Civilización romana y su pervivencia'),
-- Griego I
('1º Bachillerato','Griego','Alfabeto, fonética y acentuación'),
('1º Bachillerato','Griego','Flexión nominal y verbal'),
('1º Bachillerato','Griego','Sintaxis griega'),
('1º Bachillerato','Griego','Traducción de textos'),
('1º Bachillerato','Griego','Historia y sociedad de Grecia'),
('1º Bachillerato','Griego','Mitología'),
('1º Bachillerato','Griego','Helenismos y etimología científica'),
-- Dibujo Técnico I
('1º Bachillerato','Dibujo Técnico','Instrumental y CAD'),
('1º Bachillerato','Dibujo Técnico','Trazados geométricos, tangencias y curvas cónicas'),
('1º Bachillerato','Dibujo Técnico','Sistema diédrico'),
('1º Bachillerato','Dibujo Técnico','Sistema axonométrico'),
('1º Bachillerato','Dibujo Técnico','Sistema cónico'),
-- Dibujo Artístico I
('1º Bachillerato','Dibujo Artístico','El dibujo en la historia del arte'),
('1º Bachillerato','Dibujo Artístico','Línea, mancha y textura'),
('1º Bachillerato','Dibujo Artístico','Encuadre y dibujo del natural'),
('1º Bachillerato','Dibujo Artístico','La figura humana'),
('1º Bachillerato','Dibujo Artístico','Luz, claroscuro y perspectiva'),
('1º Bachillerato','Dibujo Artístico','Color en el dibujo'),
('1º Bachillerato','Dibujo Artístico','Proyecto artístico'),
-- Volumen
('1º Bachillerato','Volumen','Técnicas y materiales escultóricos'),
('1º Bachillerato','Volumen','Línea, plano y formas tridimensionales'),
('1º Bachillerato','Volumen','Escultura contemporánea: Land-Art, Arte Povera, instalación'),
('1º Bachillerato','Volumen','El vacío, la luz y el movimiento'),
('1º Bachillerato','Volumen','Proyectos tridimensionales'),
-- Cultura Audiovisual I
('1º Bachillerato','Cultura Audiovisual','Historia de la fotografía y del cine'),
('1º Bachillerato','Cultura Audiovisual','Lenguaje y códigos audiovisuales'),
('1º Bachillerato','Cultura Audiovisual','Elementos formales y expresivos de la imagen'),
('1º Bachillerato','Cultura Audiovisual','Narrativa audiovisual y guion'),
('1º Bachillerato','Cultura Audiovisual','Producción audiovisual por fases'),
('1º Bachillerato','Cultura Audiovisual','Análisis crítico de mensajes audiovisuales');

-- ============================================================
-- DATOS: 2º BACHILLERATO
-- ============================================================

INSERT INTO public.curriculo_temas (curso, asignatura, tema) VALUES
-- Lengua (II)
('2º Bachillerato','Lengua Castellana y Literatura','El texto y sus propiedades'),
('2º Bachillerato','Lengua Castellana y Literatura','Literatura del siglo XX y XXI'),
('2º Bachillerato','Lengua Castellana y Literatura','Comentario de texto'),
('2º Bachillerato','Lengua Castellana y Literatura','Norma y uso del español'),
-- Valenciano II
('2º Bachillerato','Valenciano','El text i les seues propietats'),
('2º Bachillerato','Valenciano','Literatura valenciana del segle XX i XXI'),
('2º Bachillerato','Valenciano','Comentari de text'),
('2º Bachillerato','Valenciano','Norma i ús del valencià'),
-- Inglés II
('2º Bachillerato','Inglés','Comprensión y producción de textos complejos (B2-C1)'),
('2º Bachillerato','Inglés','Mediación avanzada'),
('2º Bachillerato','Inglés','Gramática y léxico de nivel avanzado'),
('2º Bachillerato','Inglés','Aspectos socioculturales comparados'),
-- Historia de España (obligatoria 2º Bach)
('2º Bachillerato','Historia de España','Raíces históricas de España hasta el siglo XVIII'),
('2º Bachillerato','Historia de España','El siglo XIX: liberalismo y Restauración'),
('2º Bachillerato','Historia de España','El siglo XX: II República y Guerra Civil'),
('2º Bachillerato','Historia de España','El franquismo'),
('2º Bachillerato','Historia de España','La Transición y la España democrática'),
('2º Bachillerato','Historia de España','Método histórico y uso de fuentes'),
-- Matemáticas II (Ciencias)
('2º Bachillerato','Matemáticas','Matrices y determinantes'),
('2º Bachillerato','Matemáticas','Sistemas de ecuaciones'),
('2º Bachillerato','Matemáticas','Geometría en el espacio: vectores'),
('2º Bachillerato','Matemáticas','Límites, continuidad y derivadas'),
('2º Bachillerato','Matemáticas','Integrales'),
('2º Bachillerato','Matemáticas','Probabilidad y distribuciones'),
-- Matemáticas Aplicadas II (HH.CC.SS.)
('2º Bachillerato','Matemáticas Aplicadas','Matrices y programación lineal'),
('2º Bachillerato','Matemáticas Aplicadas','Análisis: derivadas e integrales aplicadas'),
('2º Bachillerato','Matemáticas Aplicadas','Estadística bidimensional'),
('2º Bachillerato','Matemáticas Aplicadas','Probabilidad e inferencia estadística'),
-- Física
('2º Bachillerato','Física','Gravitación universal y movimiento orbital'),
('2º Bachillerato','Física','Campo eléctrico y campo magnético'),
('2º Bachillerato','Física','Inducción electromagnética'),
('2º Bachillerato','Física','Movimiento ondulatorio y sonido'),
('2º Bachillerato','Física','Óptica geométrica'),
('2º Bachillerato','Física','Relatividad especial'),
('2º Bachillerato','Física','Física cuántica'),
('2º Bachillerato','Física','Física nuclear y de partículas'),
-- Química
('2º Bachillerato','Química','Estructura atómica y sistema periódico'),
('2º Bachillerato','Química','Enlace químico'),
('2º Bachillerato','Química','Termoquímica'),
('2º Bachillerato','Química','Cinética química'),
('2º Bachillerato','Química','Equilibrio químico'),
('2º Bachillerato','Química','Reacciones ácido-base'),
('2º Bachillerato','Química','Reacciones redox'),
('2º Bachillerato','Química','Química orgánica y polímeros'),
-- Biología
('2º Bachillerato','Biología','La base molecular de la vida: glúcidos, lípidos, proteínas, ácidos nucleicos'),
('2º Bachillerato','Biología','La célula y su fisiología'),
('2º Bachillerato','Biología','Metabolismo: catabolismo y anabolismo'),
('2º Bachillerato','Biología','Genética molecular'),
('2º Bachillerato','Biología','Microbiología'),
('2º Bachillerato','Biología','Inmunología'),
-- Geología y Ciencias Ambientales
('2º Bachillerato','Geología y Ciencias Ambientales','Métodos del trabajo geológico'),
('2º Bachillerato','Geología y Ciencias Ambientales','Tectónica de placas y deformación de rocas'),
('2º Bachillerato','Geología y Ciencias Ambientales','Riesgos naturales'),
('2º Bachillerato','Geología y Ciencias Ambientales','Modelado del relieve'),
('2º Bachillerato','Geología y Ciencias Ambientales','Atmósfera, hidrosfera y clima'),
('2º Bachillerato','Geología y Ciencias Ambientales','Recursos geológicos y su gestión sostenible'),
-- Dibujo Técnico II
('2º Bachillerato','Dibujo Técnico','Normalización, escalas y acotación'),
('2º Bachillerato','Dibujo Técnico','Sistemas de representación avanzados'),
('2º Bachillerato','Dibujo Técnico','Croquis y planos de taller'),
-- Geografía (HH.CC.SS.)
('2º Bachillerato','Geografía','Cartografía y SIG'),
('2º Bachillerato','Geografía','Relieve, clima y paisajes de España'),
('2º Bachillerato','Geografía','Recursos hídricos y medio ambiente'),
('2º Bachillerato','Geografía','Población y ciudades'),
('2º Bachillerato','Geografía','Sectores económicos'),
('2º Bachillerato','Geografía','España en la UE'),
('2º Bachillerato','Geografía','ODS y desarrollo sostenible'),
-- Historia de la Filosofía
('2º Bachillerato','Historia de la Filosofía','Presocráticos, Platón y Aristóteles'),
('2º Bachillerato','Historia de la Filosofía','Filosofía helenística'),
('2º Bachillerato','Historia de la Filosofía','Agustín y Tomás de Aquino'),
('2º Bachillerato','Historia de la Filosofía','Racionalismo y empirismo'),
('2º Bachillerato','Historia de la Filosofía','Kant e Ilustración'),
('2º Bachillerato','Historia de la Filosofía','Marx y Nietzsche'),
('2º Bachillerato','Historia de la Filosofía','Filosofía del siglo XX y pensamiento español'),
-- Empresa y Diseño de Modelos de Negocio
('2º Bachillerato','Empresa y Diseño de Modelos de Negocio','La empresa y el emprendedor'),
('2º Bachillerato','Empresa y Diseño de Modelos de Negocio','Entorno empresarial y análisis DAFO'),
('2º Bachillerato','Empresa y Diseño de Modelos de Negocio','Áreas funcionales: producción, comercial, RRHH, financiera'),
('2º Bachillerato','Empresa y Diseño de Modelos de Negocio','Modelos de negocio e innovación'),
('2º Bachillerato','Empresa y Diseño de Modelos de Negocio','Contabilidad y finanzas básicas'),
-- Historia del Arte
('2º Bachillerato','Historia del Arte','Terminología y análisis de la obra de arte'),
('2º Bachillerato','Historia del Arte','Arte antiguo: Egipto, Grecia, Roma'),
('2º Bachillerato','Historia del Arte','Arte medieval: románico, gótico, islámico'),
('2º Bachillerato','Historia del Arte','Renacimiento y Barroco'),
('2º Bachillerato','Historia del Arte','Neoclasicismo, Romanticismo y vanguardias'),
('2º Bachillerato','Historia del Arte','Arte contemporáneo y del siglo XXI'),
-- Latín II
('2º Bachillerato','Latín','Morfología y sintaxis latinas avanzadas'),
('2º Bachillerato','Latín','Traducción de textos literarios latinos'),
('2º Bachillerato','Latín','Literatura latina: géneros y autores principales'),
('2º Bachillerato','Latín','Civilización romana: pervivencia del latín'),
-- Griego II
('2º Bachillerato','Griego','Morfología y sintaxis griegas avanzadas'),
('2º Bachillerato','Griego','Traducción de textos clásicos'),
('2º Bachillerato','Griego','Literatura griega: géneros y autores principales'),
('2º Bachillerato','Griego','Pervivencia del legado griego'),
-- Dibujo Artístico II
('2º Bachillerato','Dibujo Artístico','Dibujo del natural avanzado'),
('2º Bachillerato','Dibujo Artístico','La figura humana en movimiento'),
('2º Bachillerato','Dibujo Artístico','Técnicas mixtas y experimentación'),
('2º Bachillerato','Dibujo Artístico','Proyecto artístico final'),
-- Cultura Audiovisual II
('2º Bachillerato','Cultura Audiovisual','Análisis avanzado de productos audiovisuales'),
('2º Bachillerato','Cultura Audiovisual','El cine como arte y como industria'),
('2º Bachillerato','Cultura Audiovisual','Producción audiovisual: cortometraje o documental'),
('2º Bachillerato','Cultura Audiovisual','Los nuevos medios y la cultura digital'),
-- Diseño
('2º Bachillerato','Diseño','Concepto e historia del diseño'),
('2º Bachillerato','Diseño','Sintaxis visual, forma y color'),
('2º Bachillerato','Diseño','Metodología proyectual'),
('2º Bachillerato','Diseño','Diseño gráfico'),
('2º Bachillerato','Diseño','Diseño de producto'),
('2º Bachillerato','Diseño','Diseño de interiores');
