-- Datos del currículo de temas
-- Ejecutar en: Supabase Dashboard → SQL Editor
-- Requisito previo: haber ejecutado 20260804_curriculo_temas.sql

INSERT INTO public.curriculo_temas (etapa, curso, modalidad, asignatura, fiabilidad, bloque, tema, añadido) VALUES

-- ==================== PRIMARIA ====================
('Primaria','1º a 6º Primaria',NULL,'Matemáticas','G','Sentido numérico','Números y conteo: naturales hasta 999 (1er ciclo), hasta millones, decimales y fracciones (2º-3er ciclo)',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Matemáticas','G','Sentido numérico','Operaciones: suma y resta con sentido; multiplicación y división',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Matemáticas','G','Sentido numérico','Cálculo mental y estimación',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Matemáticas','G','Sentido numérico','Fracciones, decimales y porcentajes',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Matemáticas','G','Sentido de la medida','Medida: longitud, masa, capacidad, tiempo y dinero; sistema métrico decimal',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Matemáticas','G','Sentido de la medida','Medida de ángulos, superficie y volumen',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Matemáticas','G','Sentido espacial','Figuras planas y cuerpos geométricos: elementos y propiedades',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Matemáticas','G','Sentido espacial','Localización, coordenadas y movimientos en el plano',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Matemáticas','G','Sentido algebraico','Patrones, series y primeras expresiones algebraicas; resolución de problemas y modelización',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Matemáticas','G','Sentido estocástico','Datos: tablas, gráficos y medidas simples; azar y probabilidad intuitiva',FALSE),

('Primaria','1º a 6º Primaria',NULL,'Lengua Castellana y Literatura','G','Las lenguas y sus hablantes','Diversidad lingüística de España y del entorno; actitudes ante las lenguas',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Lengua Castellana y Literatura','G','Comunicación','Comprensión oral y escrita de textos',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Lengua Castellana y Literatura','G','Comunicación','Expresión y producción de textos orales y escritos',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Lengua Castellana y Literatura','G','Comunicación','Alfabetización mediática e informacional; búsqueda de información y biblioteca',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Lengua Castellana y Literatura','G','Educación literaria','Lectura de obras infantiles; itinerarios lectores; interpretación de textos literarios',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Lengua Castellana y Literatura','G','Educación literaria','Escritura creativa con intención literaria',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Lengua Castellana y Literatura','G','Reflexión sobre la lengua','Vocabulario, ortografía, gramática y puntuación; coherencia y cohesión',FALSE),

('Primaria','1º a 6º Primaria',NULL,'Valencià: Llengua i Literatura','G','Les llengües i els seus parlants','Les llengües i els seus parlants; plurilingüisme i actituds lingüístiques',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Valencià: Llengua i Literatura','G','Comunicació','Comprensió oral i escrita de textos',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Valencià: Llengua i Literatura','G','Comunicació','Expressió i producció de textos orals i escrits',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Valencià: Llengua i Literatura','G','Comunicació','Alfabetització mediàtica i cerca d''informació',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Valencià: Llengua i Literatura','G','Educació literària','Lectura d''obres en valencià; itineraris lectors',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Valencià: Llengua i Literatura','G','Educació literària','Escriptura creativa amb intenció literària',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Valencià: Llengua i Literatura','G','Reflexió sobre la llengua','Vocabulari, ortografia, gramàtica i puntuació en valencià',FALSE),

('Primaria','1º a 6º Primaria',NULL,'Inglés','G','Comunicación','Comprensión oral y escrita de textos sencillos',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Inglés','G','Comunicación','Producción e interacción oral y escrita; funciones comunicativas básicas',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Inglés','G','Comunicación','Vocabulario y estructuras elementales por campos temáticos',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Inglés','G','Comunicación','Estrategias de mediación y de comprensión',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Inglés','G','Plurilingüismo','Comparación entre lenguas del repertorio propio',FALSE),
('Primaria','1º a 6º Primaria',NULL,'Inglés','G','Interculturalidad','La lengua extranjera como medio de relación con otras culturas',FALSE),

-- ==================== 1º ESO ====================
('ESO','1º ESO',NULL,'Matemáticas','G','Sentido numérico','Números naturales, enteros y fracciones',FALSE),
('ESO','1º ESO',NULL,'Matemáticas','G','Sentido numérico','Divisibilidad',FALSE),
('ESO','1º ESO',NULL,'Matemáticas','G','Sentido numérico','Potencias y raíces',FALSE),
('ESO','1º ESO',NULL,'Matemáticas','G','Sentido numérico','Proporcionalidad y porcentajes',FALSE),
('ESO','1º ESO',NULL,'Matemáticas','G','Sentido algebraico','Iniciación al álgebra: expresiones y ecuaciones sencillas',FALSE),
('ESO','1º ESO',NULL,'Matemáticas','G','Sentido espacial','Figuras planas: perímetros y áreas',FALSE),
('ESO','1º ESO',NULL,'Matemáticas','G','Sentido espacial','Sistema de coordenadas',FALSE),
('ESO','1º ESO',NULL,'Matemáticas','G','Sentido estocástico','Tablas y gráficos estadísticos',FALSE),
('ESO','1º ESO',NULL,'Matemáticas','G','Sentido estocástico','Azar y probabilidad',FALSE),
('ESO','1º ESO',NULL,'Matemáticas','G','Sentido socioafectivo','Trabajo en equipo y gestión emocional en matemáticas',FALSE),

('ESO','1º ESO',NULL,'Lengua Castellana y Literatura','G','Las lenguas y sus hablantes','Realidad plurilingüe de España',FALSE),
('ESO','1º ESO',NULL,'Lengua Castellana y Literatura','G','Comunicación','Comunicación oral: escuchar y hablar',FALSE),
('ESO','1º ESO',NULL,'Lengua Castellana y Literatura','G','Comunicación','Comprensión lectora y producción escrita',FALSE),
('ESO','1º ESO',NULL,'Lengua Castellana y Literatura','G','Comunicación','El texto narrativo y descriptivo',FALSE),
('ESO','1º ESO',NULL,'Lengua Castellana y Literatura','G','Educación literaria','Géneros literarios',FALSE),
('ESO','1º ESO',NULL,'Lengua Castellana y Literatura','G','Educación literaria','Lectura de obras literarias',FALSE),
('ESO','1º ESO',NULL,'Lengua Castellana y Literatura','G','Reflexión sobre la lengua','Gramática: categorías y oración simple',FALSE),
('ESO','1º ESO',NULL,'Lengua Castellana y Literatura','G','Reflexión sobre la lengua','Léxico y ortografía',FALSE),

('ESO','1º ESO',NULL,'Valencià: Llengua i Literatura','G','Les llengües i els seus parlants','Realitat plurilingüe d''Espanya',FALSE),
('ESO','1º ESO',NULL,'Valencià: Llengua i Literatura','G','Comunicació','Comunicació oral: escoltar i parlar',FALSE),
('ESO','1º ESO',NULL,'Valencià: Llengua i Literatura','G','Comunicació','Comprensió lectora i producció escrita',FALSE),
('ESO','1º ESO',NULL,'Valencià: Llengua i Literatura','G','Comunicació','El text narratiu i descriptiu',FALSE),
('ESO','1º ESO',NULL,'Valencià: Llengua i Literatura','G','Educació literària','Gèneres literaris',FALSE),
('ESO','1º ESO',NULL,'Valencià: Llengua i Literatura','G','Educació literària','Lectura d''obres literàries en valencià',FALSE),
('ESO','1º ESO',NULL,'Valencià: Llengua i Literatura','G','Reflexió sobre la llengua','Gramàtica: categories i oració simple',FALSE),
('ESO','1º ESO',NULL,'Valencià: Llengua i Literatura','G','Reflexió sobre la llengua','Lèxic i ortografia valenciana',FALSE),

('ESO','1º ESO',NULL,'Inglés','G','Comunicación','Comprensión oral y escrita',FALSE),
('ESO','1º ESO',NULL,'Inglés','G','Comunicación','Producción e interacción oral y escrita',FALSE),
('ESO','1º ESO',NULL,'Inglés','G','Comunicación','Funciones comunicativas cotidianas',FALSE),
('ESO','1º ESO',NULL,'Inglés','G','Comunicación','Gramática y léxico de nivel básico',FALSE),
('ESO','1º ESO',NULL,'Inglés','G','Plurilingüismo','Estrategias de mediación',FALSE),
('ESO','1º ESO',NULL,'Inglés','G','Plurilingüismo','Comparación entre lenguas',FALSE),
('ESO','1º ESO',NULL,'Inglés','G','Interculturalidad','Aspectos culturales anglófonos',FALSE),

('ESO','1º ESO',NULL,'Biología y Geología','G','Destrezas científicas','Método científico y trabajo de laboratorio',FALSE),
('ESO','1º ESO',NULL,'Biología y Geología','G','Geología','La Tierra en el universo y el Sistema Solar',FALSE),
('ESO','1º ESO',NULL,'Biología y Geología','G','Geología','La geosfera: minerales y rocas',FALSE),
('ESO','1º ESO',NULL,'Biología y Geología','G','Geología','La atmósfera',FALSE),
('ESO','1º ESO',NULL,'Biología y Geología','G','Geología','La hidrosfera',FALSE),
('ESO','1º ESO',NULL,'Biología y Geología','G','Biodiversidad','La célula',FALSE),
('ESO','1º ESO',NULL,'Biología y Geología','G','Biodiversidad','Clasificación de los seres vivos: los cinco reinos',FALSE),
('ESO','1º ESO',NULL,'Biología y Geología','G','Biodiversidad','Invertebrados y vertebrados',FALSE),
('ESO','1º ESO',NULL,'Biología y Geología','G','Biodiversidad','Las plantas',FALSE),
('ESO','1º ESO',NULL,'Biología y Geología','G','Biodiversidad','Ecosistemas',FALSE),

('ESO','1º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','El planeta Tierra: relieve, clima y paisajes',FALSE),
('ESO','1º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','Medio físico de Europa y España',FALSE),
('ESO','1º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','La Prehistoria',FALSE),
('ESO','1º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','Las primeras civilizaciones: Mesopotamia y Egipto',FALSE),
('ESO','1º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','Grecia',FALSE),
('ESO','1º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','Roma',FALSE),

('ESO','1º ESO',NULL,'Francés - 2ª Lengua Extranjera','G','Comunicación','Iniciación a la comprensión y producción oral',FALSE),
('ESO','1º ESO',NULL,'Francés - 2ª Lengua Extranjera','G','Comunicación','Funciones comunicativas básicas',FALSE),
('ESO','1º ESO',NULL,'Francés - 2ª Lengua Extranjera','G','Comunicación','Vocabulario elemental por campos temáticos',FALSE),
('ESO','1º ESO',NULL,'Francés - 2ª Lengua Extranjera','G','Interculturalidad','Cultura francófona',FALSE),

-- ==================== 2º ESO ====================
('ESO','2º ESO',NULL,'Matemáticas','G','Sentido numérico','Números enteros, fracciones y decimales',FALSE),
('ESO','2º ESO',NULL,'Matemáticas','G','Sentido numérico','Proporcionalidad',FALSE),
('ESO','2º ESO',NULL,'Matemáticas','G','Sentido numérico','Potencias',FALSE),
('ESO','2º ESO',NULL,'Matemáticas','G','Sentido algebraico','Álgebra: ecuaciones de primer grado',FALSE),
('ESO','2º ESO',NULL,'Matemáticas','G','Sentido espacial','Teorema de Pitágoras',FALSE),
('ESO','2º ESO',NULL,'Matemáticas','G','Sentido espacial','Figuras y cuerpos geométricos: áreas y volúmenes',FALSE),
('ESO','2º ESO',NULL,'Matemáticas','G','Sentido algebraico','Funciones y gráficas',FALSE),
('ESO','2º ESO',NULL,'Matemáticas','G','Sentido estocástico','Estadística y probabilidad',FALSE),

('ESO','2º ESO',NULL,'Lengua Castellana y Literatura','G','Comunicación','Comunicación oral y escrita',FALSE),
('ESO','2º ESO',NULL,'Lengua Castellana y Literatura','G','Comunicación','Tipologías textuales',FALSE),
('ESO','2º ESO',NULL,'Lengua Castellana y Literatura','G','Comunicación','El texto instructivo y expositivo',FALSE),
('ESO','2º ESO',NULL,'Lengua Castellana y Literatura','G','Educación literaria','Géneros literarios: narrativa, lírica y teatro',FALSE),
('ESO','2º ESO',NULL,'Lengua Castellana y Literatura','G','Reflexión sobre la lengua','Gramática: sintaxis de la oración simple',FALSE),
('ESO','2º ESO',NULL,'Lengua Castellana y Literatura','G','Reflexión sobre la lengua','Léxico y ortografía',FALSE),

('ESO','2º ESO',NULL,'Valencià: Llengua i Literatura','G','Comunicació','Comunicació oral i escrita',FALSE),
('ESO','2º ESO',NULL,'Valencià: Llengua i Literatura','G','Comunicació','Tipologies textuals',FALSE),
('ESO','2º ESO',NULL,'Valencià: Llengua i Literatura','G','Comunicació','El text instructiu i expositiu',FALSE),
('ESO','2º ESO',NULL,'Valencià: Llengua i Literatura','G','Educació literària','Gèneres literaris: narrativa, lírica i teatre',FALSE),
('ESO','2º ESO',NULL,'Valencià: Llengua i Literatura','G','Reflexió sobre la llengua','Gramàtica: sintaxi de l''oració simple',FALSE),
('ESO','2º ESO',NULL,'Valencià: Llengua i Literatura','G','Reflexió sobre la llengua','Lèxic i ortografia valenciana',FALSE),

('ESO','2º ESO',NULL,'Inglés','G','Comunicación','Comprensión oral y escrita',FALSE),
('ESO','2º ESO',NULL,'Inglés','G','Comunicación','Producción e interacción oral y escrita',FALSE),
('ESO','2º ESO',NULL,'Inglés','G','Comunicación','Funciones comunicativas cotidianas',FALSE),
('ESO','2º ESO',NULL,'Inglés','G','Comunicación','Gramática y léxico de nivel',FALSE),
('ESO','2º ESO',NULL,'Inglés','G','Plurilingüismo','Estrategias de mediación',FALSE),
('ESO','2º ESO',NULL,'Inglés','G','Interculturalidad','Aspectos culturales anglófonos',FALSE),

('ESO','2º ESO',NULL,'Física y Química','I','Las destrezas científicas básicas','Método científico, magnitudes y Sistema Internacional',FALSE),
('ESO','2º ESO',NULL,'Física y Química','I','La materia','Propiedades de la materia y estados de agregación',FALSE),
('ESO','2º ESO',NULL,'Física y Química','I','La materia','Modelo cinético-molecular',FALSE),
('ESO','2º ESO',NULL,'Física y Química','I','La materia','Sustancias puras y mezclas',FALSE),
('ESO','2º ESO',NULL,'Física y Química','I','La materia','Separación de mezclas',FALSE),
('ESO','2º ESO',NULL,'Física y Química','I','La energía','La energía y sus formas',FALSE),
('ESO','2º ESO',NULL,'Física y Química','I','El cambio','El cambio físico y químico: introducción a la reacción química',FALSE),

('ESO','2º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','La Europa feudal',FALSE),
('ESO','2º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','El islam y Al-Ándalus',FALSE),
('ESO','2º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','Los reinos cristianos peninsulares',FALSE),
('ESO','2º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','La ciudad medieval',FALSE),
('ESO','2º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','El Renacimiento y el Humanismo',FALSE),
('ESO','2º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','La Edad Moderna (siglos XV-XVIII)',FALSE),
('ESO','2º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','Los descubrimientos geográficos',FALSE),

-- ==================== 3º ESO ====================
('ESO','3º ESO',NULL,'Matemáticas','G','Sentido numérico','Números racionales y reales',FALSE),
('ESO','3º ESO',NULL,'Matemáticas','G','Sentido numérico','Potencias y notación científica',FALSE),
('ESO','3º ESO',NULL,'Matemáticas','G','Sentido algebraico','Polinomios y ecuaciones/sistemas de ecuaciones',FALSE),
('ESO','3º ESO',NULL,'Matemáticas','G','Sentido algebraico','Sucesiones',FALSE),
('ESO','3º ESO',NULL,'Matemáticas','G','Sentido espacial','Geometría: semejanza y cuerpos geométricos',FALSE),
('ESO','3º ESO',NULL,'Matemáticas','G','Sentido algebraico','Funciones lineales y cuadráticas',FALSE),
('ESO','3º ESO',NULL,'Matemáticas','G','Sentido estocástico','Estadística y probabilidad',FALSE),

('ESO','3º ESO',NULL,'Lengua Castellana y Literatura','G','Las lenguas y sus hablantes','Variedades del español y lenguas de España',FALSE),
('ESO','3º ESO',NULL,'Lengua Castellana y Literatura','G','Comunicación','Comunicación oral formal',FALSE),
('ESO','3º ESO',NULL,'Lengua Castellana y Literatura','G','Comunicación','El texto expositivo-argumentativo',FALSE),
('ESO','3º ESO',NULL,'Lengua Castellana y Literatura','G','Educación literaria','Literatura medieval y de los Siglos de Oro',FALSE),
('ESO','3º ESO',NULL,'Lengua Castellana y Literatura','G','Reflexión sobre la lengua','Gramática: sintaxis de la oración',FALSE),
('ESO','3º ESO',NULL,'Lengua Castellana y Literatura','G','Reflexión sobre la lengua','Léxico y ortografía',FALSE),

('ESO','3º ESO',NULL,'Valencià: Llengua i Literatura','G','Les llengües i els seus parlants','Varietats del valencià i llengues d''Espanya',FALSE),
('ESO','3º ESO',NULL,'Valencià: Llengua i Literatura','G','Comunicació','Comunicació oral formal',FALSE),
('ESO','3º ESO',NULL,'Valencià: Llengua i Literatura','G','Comunicació','El text expositiu-argumentatiu',FALSE),
('ESO','3º ESO',NULL,'Valencià: Llengua i Literatura','G','Educació literària','Literatura valenciana medieval',FALSE),
('ESO','3º ESO',NULL,'Valencià: Llengua i Literatura','G','Reflexió sobre la llengua','Gramàtica: sintaxi de l''oració',FALSE),
('ESO','3º ESO',NULL,'Valencià: Llengua i Literatura','G','Reflexió sobre la llengua','Lèxic i ortografia valenciana',FALSE),

('ESO','3º ESO',NULL,'Inglés','G','Comunicación','Comprensión oral y escrita de nivel intermedio',FALSE),
('ESO','3º ESO',NULL,'Inglés','G','Comunicación','Producción e interacción oral y escrita',FALSE),
('ESO','3º ESO',NULL,'Inglés','G','Comunicación','Funciones comunicativas de nivel intermedio',FALSE),
('ESO','3º ESO',NULL,'Inglés','G','Comunicación','Gramática y léxico de nivel intermedio',FALSE),
('ESO','3º ESO',NULL,'Inglés','G','Plurilingüismo','Estrategias de mediación',FALSE),
('ESO','3º ESO',NULL,'Inglés','G','Interculturalidad','Aspectos culturales anglófonos',FALSE),

('ESO','3º ESO',NULL,'Biología y Geología','G','Biología: cuerpo humano','La célula y los tejidos',FALSE),
('ESO','3º ESO',NULL,'Biología y Geología','G','Biología: cuerpo humano','Salud y enfermedad',FALSE),
('ESO','3º ESO',NULL,'Biología y Geología','G','Biología: cuerpo humano','Nutrición: aparatos digestivo, respiratorio, circulatorio y excretor',FALSE),
('ESO','3º ESO',NULL,'Biología y Geología','G','Biología: cuerpo humano','Relación: sistema nervioso, endocrino y órganos de los sentidos',FALSE),
('ESO','3º ESO',NULL,'Biología y Geología','G','Biología: cuerpo humano','Reproducción humana',FALSE),
('ESO','3º ESO',NULL,'Biología y Geología','G','Geología','Geología: relieve y modelado',FALSE),
('ESO','3º ESO',NULL,'Biología y Geología','G','Geología','Geología interna',FALSE),

('ESO','3º ESO',NULL,'Física y Química','G','Las destrezas científicas básicas','Método científico',FALSE),
('ESO','3º ESO',NULL,'Física y Química','G','La materia','Estructura atómica, isótopos y modelos atómicos',FALSE),
('ESO','3º ESO',NULL,'Física y Química','G','La materia','El Sistema Periódico',FALSE),
('ESO','3º ESO',NULL,'Física y Química','G','La materia','Uniones entre átomos: enlace químico',FALSE),
('ESO','3º ESO',NULL,'Física y Química','G','La materia','Formulación y nomenclatura inorgánica (IUPAC)',FALSE),
('ESO','3º ESO',NULL,'Física y Química','G','El cambio','La reacción química y estequiometría',FALSE),
('ESO','3º ESO',NULL,'Física y Química','G','El cambio','Ley de conservación de la masa',FALSE),
('ESO','3º ESO',NULL,'Física y Química','G','El cambio','Química, sociedad y medioambiente',FALSE),

('ESO','3º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','Población y demografía',FALSE),
('ESO','3º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','El espacio urbano y rural',FALSE),
('ESO','3º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','Los sectores económicos',FALSE),
('ESO','3º ESO',NULL,'Geografía e Historia','G','Retos del mundo actual','Globalización',FALSE),
('ESO','3º ESO',NULL,'Geografía e Historia','G','Compromiso cívico','Organización política',FALSE),
('ESO','3º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','España y la Comunitat Valenciana',FALSE),
('ESO','3º ESO',NULL,'Geografía e Historia','G','Retos del mundo actual','Los ODS',FALSE),

-- ==================== 4º ESO ====================
('ESO','4º ESO',NULL,'Matemáticas A','G','Sentido numérico','Números reales y porcentajes',FALSE),
('ESO','4º ESO',NULL,'Matemáticas A','G','Sentido numérico','Matemática financiera básica',FALSE),
('ESO','4º ESO',NULL,'Matemáticas A','G','Sentido algebraico','Álgebra aplicada',FALSE),
('ESO','4º ESO',NULL,'Matemáticas A','G','Sentido algebraico','Funciones y gráficas',FALSE),
('ESO','4º ESO',NULL,'Matemáticas A','G','Sentido estocástico','Estadística y probabilidad aplicadas',FALSE),

('ESO','4º ESO',NULL,'Matemáticas B','G','Sentido numérico','Números reales y radicales',FALSE),
('ESO','4º ESO',NULL,'Matemáticas B','G','Sentido algebraico','Polinomios y fracciones algebraicas',FALSE),
('ESO','4º ESO',NULL,'Matemáticas B','G','Sentido algebraico','Ecuaciones, inecuaciones y sistemas',FALSE),
('ESO','4º ESO',NULL,'Matemáticas B','G','Sentido espacial','Trigonometría',FALSE),
('ESO','4º ESO',NULL,'Matemáticas B','G','Sentido espacial','Geometría analítica',FALSE),
('ESO','4º ESO',NULL,'Matemáticas B','G','Sentido algebraico','Funciones: polinómicas, racionales, exponenciales y logarítmicas',FALSE),
('ESO','4º ESO',NULL,'Matemáticas B','G','Sentido estocástico','Estadística y probabilidad',FALSE),

('ESO','4º ESO',NULL,'Lengua Castellana y Literatura','G','Comunicación','Tipologías textuales avanzadas',FALSE),
('ESO','4º ESO',NULL,'Lengua Castellana y Literatura','G','Educación literaria','Literatura siglo XVIII: la Ilustración',FALSE),
('ESO','4º ESO',NULL,'Lengua Castellana y Literatura','G','Educación literaria','Literatura siglo XIX: Romanticismo y Realismo',FALSE),
('ESO','4º ESO',NULL,'Lengua Castellana y Literatura','G','Educación literaria','Literatura siglo XX: Generación del 98, del 27 y contemporánea',FALSE),
('ESO','4º ESO',NULL,'Lengua Castellana y Literatura','G','Reflexión sobre la lengua','Gramática: sintaxis de la oración compuesta',FALSE),
('ESO','4º ESO',NULL,'Lengua Castellana y Literatura','G','Reflexión sobre la lengua','Léxico y ortografía',FALSE),

('ESO','4º ESO',NULL,'Valencià: Llengua i Literatura','G','Comunicació','Tipologies textuals avançades',FALSE),
('ESO','4º ESO',NULL,'Valencià: Llengua i Literatura','G','Educació literària','Literatura valenciana contemporànea',FALSE),
('ESO','4º ESO',NULL,'Valencià: Llengua i Literatura','G','Reflexió sobre la llengua','Gramàtica: sintaxi de l''oració composta',FALSE),
('ESO','4º ESO',NULL,'Valencià: Llengua i Literatura','G','Reflexió sobre la llengua','Lèxic i ortografia valenciana avançada',FALSE),

('ESO','4º ESO',NULL,'Inglés','G','Comunicación','Comprensión oral y escrita de nivel B1',FALSE),
('ESO','4º ESO',NULL,'Inglés','G','Comunicación','Producción e interacción oral y escrita',FALSE),
('ESO','4º ESO',NULL,'Inglés','G','Comunicación','Funciones comunicativas avanzadas',FALSE),
('ESO','4º ESO',NULL,'Inglés','G','Comunicación','Gramática y léxico de nivel B1',FALSE),
('ESO','4º ESO',NULL,'Inglés','G','Plurilingüismo','Estrategias de mediación',FALSE),
('ESO','4º ESO',NULL,'Inglés','G','Interculturalidad','Aspectos culturales anglófonos',FALSE),

('ESO','4º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','El siglo XVIII y las revoluciones liberales',FALSE),
('ESO','4º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','La Revolución Industrial',FALSE),
('ESO','4º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','Imperialismo y Primera Guerra Mundial',FALSE),
('ESO','4º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','El periodo de entreguerras y la Segunda Guerra Mundial',FALSE),
('ESO','4º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','La Guerra Fría y la descolonización',FALSE),
('ESO','4º ESO',NULL,'Geografía e Historia','G','Sociedades y territorios','España contemporánea (siglos XIX-XX)',FALSE),
('ESO','4º ESO',NULL,'Geografía e Historia','G','Retos del mundo actual','El mundo actual y la globalización',FALSE),

('ESO','4º ESO',NULL,'Biología y Geología','G','Biología','Evolución y genética',FALSE),
('ESO','4º ESO',NULL,'Biología y Geología','G','Biología','Genética molecular y herencia',FALSE),
('ESO','4º ESO',NULL,'Biología y Geología','G','Biología','Origen y evolución de los seres vivos',FALSE),
('ESO','4º ESO',NULL,'Biología y Geología','G','Biología','Ecología y medioambiente',FALSE),
('ESO','4º ESO',NULL,'Biología y Geología','G','Geología','Dinámica de la Tierra: tectónica de placas',FALSE),
('ESO','4º ESO',NULL,'Biología y Geología','G','Geología','Historia de la Tierra',FALSE),

('ESO','4º ESO',NULL,'Física y Química','G','La interacción','Cinemática: el movimiento y sus magnitudes',FALSE),
('ESO','4º ESO',NULL,'Física y Química','G','La interacción','Dinámica: fuerzas y leyes de Newton',FALSE),
('ESO','4º ESO',NULL,'Física y Química','G','La energía','Energía y trabajo',FALSE),
('ESO','4º ESO',NULL,'Física y Química','G','La materia','Estructura atómica y enlace',FALSE),
('ESO','4º ESO',NULL,'Física y Química','G','El cambio','Reacciones químicas',FALSE),
('ESO','4º ESO',NULL,'Física y Química','G','El cambio','Química del carbono: introducción',FALSE),

('ESO','4º ESO',NULL,'Economía y Emprendimiento','G','Las decisiones económicas','La actividad económica y el emprendimiento',FALSE),
('ESO','4º ESO',NULL,'Economía y Emprendimiento','G','Herramientas microeconómicas','Los mercados',FALSE),
('ESO','4º ESO',NULL,'Economía y Emprendimiento','G','Las decisiones económicas','Economía personal y financiera',FALSE),
('ESO','4º ESO',NULL,'Economía y Emprendimiento','G','Emprendimiento','El proyecto emprendedor',FALSE),

('ESO','4º ESO',NULL,'Latín','G','Plurilingüismo','El latín y las lenguas romances',FALSE),
('ESO','4º ESO',NULL,'Latín','G','El texto: comprensión y traducción','Morfología y sintaxis básica del latín',FALSE),
('ESO','4º ESO',NULL,'Latín','G','El texto: comprensión y traducción','Textos latinos y traducción',FALSE),
('ESO','4º ESO',NULL,'Latín','G','Plurilingüismo','Léxico y etimología latina',FALSE),
('ESO','4º ESO',NULL,'Latín','G','Educación literaria y cultura','Civilización romana',FALSE),

('ESO','4º ESO',NULL,'Filosofía','G','El saber filosófico','El saber filosófico',FALSE),
('ESO','4º ESO',NULL,'Filosofía','G','Antropología filosófica','El ser humano',FALSE),
('ESO','4º ESO',NULL,'Filosofía','G','Teoría del conocimiento','Conocimiento y verdad',FALSE),
('ESO','4º ESO',NULL,'Filosofía','G','La acción: ética y política','Ética y filosofía moral',FALSE),
('ESO','4º ESO',NULL,'Filosofía','G','La acción: ética y política','Filosofía política',FALSE),
('ESO','4º ESO',NULL,'Filosofía','G','Estética','Estética',FALSE),

-- ==================== 1º BACHILLERATO ====================
('Bachillerato','1º Bachillerato',NULL,'Lengua Castellana y Literatura','G','Comunicación','Comunicación y tipologías textuales',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Lengua Castellana y Literatura','G','Las lenguas y sus hablantes','Variedades del español',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Lengua Castellana y Literatura','G','Educación literaria','Literatura de la Edad Media al siglo XIX',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Lengua Castellana y Literatura','G','Reflexión sobre la lengua','Gramática: sintaxis avanzada',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Valencià: Llengua i Literatura','G','Comunicació','Comunicació i textos acadèmics',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Valencià: Llengua i Literatura','G','Les llengues i els seus parlants','Sociolingüística del valencià',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Valencià: Llengua i Literatura','G','Educació literària','Literatura valenciana clàssica i contemporànea',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Valencià: Llengua i Literatura','G','Comunicació','Comentari de text',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Inglés','G','Comunicación','Comprensión y producción de textos complejos',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Inglés','G','Plurilingüismo','Mediación lingüística',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Inglés','G','Comunicación','Gramática y léxico B1-B2',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Inglés','G','Interculturalidad','Aspectos socioculturales anglófonos',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Filosofía','G','El saber filosófico','Qué es la filosofía',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Filosofía','G','El saber filosófico','Lógica y argumentación',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Filosofía','G','El ser humano y el conocimiento','Teoría del conocimiento',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Filosofía','G','El ser humano y el conocimiento','Metafísica y ontología',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Filosofía','G','Antropología filosófica','Antropología filosófica',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Filosofía','G','La acción: ética y política','Ética',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Filosofía','G','La acción: ética y política','Filosofía política',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Filosofía','G','Estética','Estética',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Matemáticas I','G','Sentido numérico','Números reales, complejos y logaritmos',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Matemáticas I','G','Sentido algebraico','Álgebra y ecuaciones',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Matemáticas I','G','Sentido espacial/geométrico','Trigonometría',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Matemáticas I','G','Sentido espacial/geométrico','Geometría analítica plana',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Matemáticas I','G','Sentido algebraico','Funciones, límites y derivadas',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Matemáticas I','G','Sentido estocástico','Estadística bidimensional y probabilidad',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Matemáticas Aplicadas a las CCSS I','G','Sentido numérico','Números reales y matemática financiera',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Matemáticas Aplicadas a las CCSS I','G','Sentido algebraico','Álgebra: matrices, sistemas y programación lineal',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Matemáticas Aplicadas a las CCSS I','G','Sentido algebraico','Funciones, límites y derivadas',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Matemáticas Aplicadas a las CCSS I','G','Sentido estocástico','Estadística descriptiva',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Matemáticas Aplicadas a las CCSS I','G','Sentido estocástico','Probabilidad',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Historia del Mundo Contemporáneo','G','Sociedades en el tiempo','Crisis del Antiguo Régimen y revoluciones liberales',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Historia del Mundo Contemporáneo','G','Sociedades en el tiempo','La Revolución Industrial',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Historia del Mundo Contemporáneo','G','Sociedades en el tiempo','El imperialismo',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Historia del Mundo Contemporáneo','G','Sociedades en el tiempo','Las guerras mundiales y el periodo de entreguerras',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Historia del Mundo Contemporáneo','G','Sociedades en el tiempo','La Guerra Fría',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Historia del Mundo Contemporáneo','G','Retos del mundo actual','La descolonización',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Historia del Mundo Contemporáneo','G','Retos del mundo actual','El mundo actual y la globalización',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Economía','G','Las decisiones económicas','Escasez y costes de oportunidad',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Economía','G','Las decisiones económicas','Sistemas económicos',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Economía','G','Herramientas microeconómicas','Oferta, demanda y mercados',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Economía','G','Herramientas macroeconómicas','PIB y renta nacional',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Economía','G','Desequilibrios económicos','Inflación y desempleo',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Economía','G','Desequilibrios económicos','Política fiscal y monetaria',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Economía','G','Economía mundial','Comercio internacional y globalización',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Economía','G','Economía mundial','Economía española y valenciana',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Literatura Universal','G','Temas y géneros','Literatura del yo y poesía lírica',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Literatura Universal','G','Temas y géneros','El teatro y sus géneros',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Literatura Universal','G','Temas y géneros','Lo real y lo fantástico en la narrativa',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Literatura Universal','G','Lectura autónoma','Itinerarios temáticos intertextuales',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Literatura Universal','G','Lectura autónoma','Relaciones literatura-otras artes',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Literatura Universal','G','Lectura autónoma','Creación literaria propia',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Latín I','G','El texto: comprensión y traducción','Morfología y sintaxis del latín',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Latín I','G','El texto: comprensión y traducción','Traducción de textos latinos graduados',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Latín I','G','Plurilingüismo','Étimos y latinismos',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Latín I','G','Educación literaria','Literatura latina',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Latín I','G','Cultura clásica','Civilización romana y su pervivencia',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Griego I','G','El texto: comprensión y traducción','Alfabeto, fonética y acentuación griega',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Griego I','G','El texto: comprensión y traducción','Flexión nominal griega',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Griego I','G','El texto: comprensión y traducción','Flexión verbal griega',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Griego I','G','El texto: comprensión y traducción','Sintaxis griega',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Griego I','G','El texto: comprensión y traducción','Traducción de textos griegos',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Griego I','G','La antigua Grecia','Historia y sociedad de la antigua Grecia',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Griego I','G','La antigua Grecia','Mitología griega',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Griego I','G','Legado y patrimonio','Helenismos y etimología científica',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Griego I','G','Legado y patrimonio','El legado clásico griego',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Dibujo Técnico I','G','Geometría métrica','Instrumental y CAD: introducción',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Dibujo Técnico I','G','Geometría métrica','Trazados geométricos, tangencias y curvas cónicas',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Dibujo Técnico I','G','Geometría proyectiva','Sistema diédrico',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Dibujo Técnico I','G','Geometría proyectiva','Sistema axonométrico y cónico',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Dibujo Técnico I','G','Normalización','Normalización, escalas y acotación',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Dibujo Técnico I','G','Normalización','Croquis y planos básicos',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Dibujo Artístico I','P','Concepto e historia del dibujo','El dibujo en la historia del arte',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Dibujo Artístico I','P','La expresión gráfica y sus recursos','Línea, mancha y textura',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Dibujo Artístico I','P','La forma','Encuadre y dibujo del natural',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Dibujo Artístico I','P','La forma','La figura humana',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Dibujo Artístico I','P','El volumen','Luz, claroscuro y perspectiva',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Dibujo Artístico I','P','El color','Color',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Dibujo Artístico I','P','Proyectos gráficos','Proyecto artístico',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Cultura Audiovisual I','G','Percepción y análisis','Historia de la fotografía y del cine',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Cultura Audiovisual I','G','Percepción y análisis','Lenguaje y códigos audiovisuales',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Cultura Audiovisual I','G','Percepción y análisis','Elementos formales y expresivos de la imagen',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Cultura Audiovisual I','G','Creación','Narrativa audiovisual y guion',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Cultura Audiovisual I','G','Creación','Producción por fases y trabajo en equipo',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Cultura Audiovisual I','G','Percepción y análisis','Análisis crítico de mensajes audiovisuales',FALSE),

('Bachillerato','1º Bachillerato',NULL,'Volumen','G','Técnicas y materiales','Técnicas y materiales escultóricos',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Volumen','G','Elementos de configuración','Línea, plano y formas tridimensionales',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Volumen','G','Análisis de la representación','Escultura contemporánea: Land-Art, Arte Povera, instalación',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Volumen','G','El volumen y el diseño','El vacío, la luz y el movimiento',FALSE),
('Bachillerato','1º Bachillerato',NULL,'Volumen','G','Proyectos de volumen','Proyectos tridimensionales',FALSE),

-- ==================== 2º BACHILLERATO ====================
('Bachillerato','2º Bachillerato',NULL,'Lengua Castellana y Literatura','G','Comunicación','El texto y sus propiedades',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Lengua Castellana y Literatura','G','Educación literaria','Literatura del siglo XX y XXI',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Lengua Castellana y Literatura','G','Comunicación','Comentario de texto y análisis literario',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Lengua Castellana y Literatura','G','Reflexión sobre la lengua','Norma y uso de la lengua',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Valencià: Llengua i Literatura','G','Comunicació','El text i les seues propietats',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Valencià: Llengua i Literatura','G','Educació literària','Literatura valenciana del segle XX i XXI',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Valencià: Llengua i Literatura','G','Comunicació','Comentari de text i anàlisi literària',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Valencià: Llengua i Literatura','G','Reflexió sobre la llengua','Norma i ús de la llengua valenciana',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Inglés','G','Comunicación','Comprensión y producción de textos complejos B2',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Inglés','G','Plurilingüismo','Mediación lingüística avanzada',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Inglés','G','Comunicación','Gramática y léxico B2',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Inglés','G','Interculturalidad','Aspectos socioculturales avanzados',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Historia de España','G','Sociedades en el tiempo','Raíces históricas de España hasta el siglo XVIII',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia de España','G','Sociedades en el tiempo','El siglo XIX: crisis del Antiguo Régimen, liberalismo y Restauración',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia de España','G','Sociedades en el tiempo','El siglo XX: II República y Guerra Civil',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia de España','G','Sociedades en el tiempo','El franquismo',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia de España','G','Sociedades en el tiempo','La Transición y la España democrática',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia de España','G','Compromiso cívico','Método histórico y uso de fuentes',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Matemáticas II','G','Sentido algebraico','Matrices y determinantes',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Matemáticas II','G','Sentido algebraico','Sistemas de ecuaciones',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Matemáticas II','G','Sentido espacial/geométrico','Geometría en el espacio: vectores',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Matemáticas II','G','Sentido algebraico','Límites y continuidad',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Matemáticas II','G','Sentido algebraico','Derivadas e integrales',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Matemáticas II','G','Sentido estocástico','Probabilidad y distribuciones',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Matemáticas Aplicadas a las CCSS II','G','Sentido algebraico','Matrices y programación lineal',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Matemáticas Aplicadas a las CCSS II','G','Sentido algebraico','Derivadas e integrales aplicadas',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Matemáticas Aplicadas a las CCSS II','G','Sentido estocástico','Estadística bidimensional',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Matemáticas Aplicadas a las CCSS II','G','Sentido estocástico','Probabilidad e inferencia estadística',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Física','G','Campo gravitatorio','Gravitación universal y movimiento orbital',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Física','G','Campo electromagnético','Campo eléctrico',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Física','G','Campo electromagnético','Campo magnético e inducción electromagnética',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Física','G','Vibraciones y ondas','Movimiento ondulatorio y sonido',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Física','G','Vibraciones y ondas','Óptica geométrica',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Física','G','Física relativista','Relatividad especial',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Física','G','Física cuántica y nuclear','Física cuántica',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Física','G','Física cuántica y nuclear','Física nuclear y de partículas',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Química','G','Enlace químico y estructura','Estructura atómica y sistema periódico',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Química','G','Enlace químico y estructura','Enlace químico',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Química','G','Características de las reacciones','Termoquímica',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Química','G','Características de las reacciones','Cinética química',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Química','G','Tipos de reacciones','Equilibrio químico',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Química','G','Tipos de reacciones','Reacciones ácido-base',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Química','G','Tipos de reacciones','Reacciones redox',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Química','G','Química orgánica','Química orgánica y polímeros',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Biología','G','Bioquímica','Base molecular de la vida: glúcidos, lípidos, proteínas y ácidos nucleicos',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Biología','G','Biología celular','La célula y su fisiología',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Biología','G','Biología celular','Metabolismo: catabolismo y anabolismo',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Biología','G','Genética','Genética molecular',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Biología','G','Microbiología','Microbiología',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Biología','G','Inmunología','Inmunología',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Geología y Ciencias Ambientales','G','Experimentación en Geología','Métodos del trabajo geológico',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Geología y Ciencias Ambientales','G','Tectónica de placas','Tectónica de placas y geodinámica interna',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Geología y Ciencias Ambientales','G','Procesos geológicos externos','Riesgos naturales',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Geología y Ciencias Ambientales','G','Procesos geológicos externos','Modelado del relieve',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Geología y Ciencias Ambientales','G','Las capas fluidas','Atmósfera, hidrosfera y clima',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Geología y Ciencias Ambientales','G','Recursos y gestión sostenible','Recursos geológicos y gestión sostenible',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Historia del Arte','G','Nos acercamos a la obra de arte','Terminología y análisis de la obra de arte',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia del Arte','G','Rituales, figura humana y res publica','Arte antiguo: Egipto, Grecia y Roma',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia del Arte','G','Religión y arte','Arte medieval: románico, gótico e islámico',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia del Arte','G','Burguesía y ciudades','Renacimiento y Barroco',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia del Arte','G','Academicismo e individualismo','Neoclasicismo, Romanticismo y vanguardias',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia del Arte','G','El mundo del arte en el siglo XXI','Arte contemporáneo y del siglo XXI',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Historia de la Filosofía','G','Filosofía Antigua','Filosofía Antigua: presocráticos, Platón y Aristóteles',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia de la Filosofía','G','Filosofía Medieval','Filosofía Medieval: Agustín de Hipona y Tomás de Aquino',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia de la Filosofía','G','Filosofía Moderna','Racionalismo y empirismo',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia de la Filosofía','G','Filosofía Moderna','Kant e Ilustración',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia de la Filosofía','G','Filosofía Contemporánea','Marx y Nietzsche',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Historia de la Filosofía','G','Filosofía Contemporánea','Filosofía del siglo XX y pensamiento español',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Geografía','G','Métodos y técnicas','Cartografía y SIG',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Geografía','G','Medio físico de España','Relieve, clima y paisajes de España',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Geografía','G','Medio físico de España','Recursos hídricos y medioambiente',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Geografía','G','España: territorio y sociedad','Población y ciudades de España',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Geografía','G','España: territorio y sociedad','Los sectores económicos de España',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Geografía','G','España en Europa y el mundo','España en la Unión Europea',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Geografía','G','Valores cívicos','ODS y retos globales',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Empresa y Diseño de Modelos de Negocio','G','Actividad emprendedora','La empresa y el emprendedor',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Empresa y Diseño de Modelos de Negocio','G','Entorno y estrategias','Entorno empresarial y análisis DAFO',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Empresa y Diseño de Modelos de Negocio','G','Áreas funcionales','Áreas funcionales de la empresa',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Empresa y Diseño de Modelos de Negocio','G','Estrategia empresarial','Modelos de negocio e innovación',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Empresa y Diseño de Modelos de Negocio','G','Áreas funcionales','Contabilidad y finanzas básicas',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Latín II','G','El texto: comprensión y traducción','Morfología y sintaxis avanzada del latín',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Latín II','G','El texto: comprensión y traducción','Traducción de textos latinos',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Latín II','G','Plurilingüismo','Étimos y latinismos',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Latín II','G','Educación literaria','Literatura latina',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Latín II','G','Cultura clásica','Civilización romana y su pervivencia',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Griego II','G','El texto: comprensión y traducción','Morfología y sintaxis avanzada del griego',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Griego II','G','El texto: comprensión y traducción','Traducción de textos griegos avanzados',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Griego II','G','La antigua Grecia','Literatura griega',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Griego II','G','La antigua Grecia','Historia de Grecia',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Griego II','G','Legado y patrimonio','Helenismos y etimología científica avanzada',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Dibujo Técnico II','G','Geometría métrica','Trazados geométricos avanzados',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Dibujo Técnico II','G','Geometría proyectiva','Sistema diédrico avanzado',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Dibujo Técnico II','G','Geometría proyectiva','Sistema axonométrico y cónico avanzado',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Dibujo Técnico II','G','Normalización','Normalización y acotación avanzada',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Dibujo Técnico II','G','Normalización','Croquis y planos de taller',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Dibujo Técnico II','G','Sistemas CAD','CAD y documentación de proyectos',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Dibujo Artístico II','P','Concepto e historia','El dibujo en la historia del arte (avanzado)',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Dibujo Artístico II','P','La expresión gráfica y sus recursos','Técnicas de dibujo avanzadas',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Dibujo Artístico II','P','La composición','Composición y sintaxis visual',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Dibujo Artístico II','P','La forma','Dibujo del natural avanzado',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Dibujo Artístico II','P','El volumen','Perspectiva y volumen',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Dibujo Artístico II','P','El color','Color avanzado',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Dibujo Artístico II','P','Proyectos gráficos','Proyecto artístico final',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Cultura Audiovisual II','G','Percepción y análisis','Historia del audiovisual contemporáneo',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Cultura Audiovisual II','G','Percepción y análisis','Lenguaje audiovisual avanzado',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Cultura Audiovisual II','G','Creación','Producción audiovisual: fases y gestión',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Cultura Audiovisual II','G','Creación','Proyecto audiovisual propio',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Cultura Audiovisual II','G','Percepción y análisis','Análisis crítico y ética mediática',FALSE),

('Bachillerato','2º Bachillerato',NULL,'Diseño','P','Evolución histórica y ámbitos','Concepto e historia del diseño',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Diseño','P','Elementos de configuración','Sintaxis visual, forma y color',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Diseño','P','Metodología del proyecto','Metodología proyectual',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Diseño','P','Diseño y comunicación gráfica','Diseño gráfico y comunicación',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Diseño','P','Diseño de producto','Diseño de producto',FALSE),
('Bachillerato','2º Bachillerato',NULL,'Diseño','P','Diseño del espacio','Diseño de interiores',FALSE);
